<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    public function run(): void
    {
        $languages = [
            '!O!ung',
            '!Xóõ',
            "'Are'are",
            "'Auhelawa",
            "A'tong",
            'A-Pucikwar',
            'Aari',
            'Aasáx',
            'Abadi',
            'Abaga',
            'Abai Sungai',
            'Abanyom',
            'Abar',
            'Abau',
            'Abaza',
            'Abellen Ayta',
            'Abidji',
            'Abinomn',
            'Abkhazian',
            'Abom',
            'Abon',
            'Abron',
            'Abu',
            "Abu' Arapesh",
            'Abua',
            'Abui',
            'Abun',
            'Abure',
            'Abureni',
            'Abé',
            "Acatepec Me'phaa",
            'Achagua',
            'Achang',
            'Ache',
            'Acheron',
            'Achi',
            'Achinese',
            'Achterhoeks',
            'Achuar-Shiwiar',
            'Achumawi',
            'Aché',
            'Acoli',
            'Adabe',
            'Adamawa Fulfulde',
            'Adamorobe Sign Language',
            'Adang',
            'Adangbe',
            'Adangme',
            'Adap',
            'Adasen',
            'Adele',
            'Adhola',
            'Adi',
            'Adioukrou',
            'Adivasi Oriya',
            'Adiwasi Garasia',
            'Adnyamathanha',
            'Adonara',
            'Aduge',
            'Adyghe',
            'Adzera',
            'Aeka',
            'Aekyom',
            'Aer',
            'Afade',
            'Afar',
            'Afghan Sign Language',
            'Afitti',
            'Afrikaans',
            'Afro-Seminole Creole',
            'Agarabi',
            'Agariya',
            'Agatu',
            'Aghem',
            'Aghu',
            'Aghul',
            'Agi',
            'Agob',
            'Agoi',
            'Aguacateco',
            'Aguaruna',
            'Aguna',
            'Agusan Manobo',
            'Agutaynen',
            'Agwagwune',
            'Ahanta',
            'Aheu',
            'Ahirani',
            'Ahtena',
            'Ahwai',
            'Ai-Cham',
            'Aighon',
            'Aikanã',
            'Aiklep',
            'Aimaq',
            'Aimele',
            'Aimol',
            'Ainbai',
            'Ainu (China)',
            'Ainu (Japan)',
        ];

        foreach ($languages as $language) {
            DB::table('languages')->insert([
                'name' => $language,
            ]);
        }
    }
}
